package agentsessions

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const (
	claudeSID  = "7caa5648-8121-42c3-8868-d270b407a029"
	claudeSID2 = "11111111-2222-4333-8444-555555555555"
	claudeSID3 = "22222222-3333-4444-8555-666666666666"
	codexSID   = "019a1b2c-3d4e-5f60-7182-93a4b5c6d7e8"
	codexSub   = "019a1b2c-3d4e-5f60-7182-000000000001"
)

func line(t *testing.T, v any) string {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return string(b) + "\n"
}

func claudeUser(content any, extra map[string]any) map[string]any {
	m := map[string]any{"type": "user", "cwd": `C:\work\shop`, "sessionId": claudeSID,
		"message": map[string]any{"role": "user", "content": content}}
	for k, v := range extra {
		m[k] = v
	}
	return m
}

func claudeAssistant(blocks ...map[string]any) map[string]any {
	return map[string]any{"type": "assistant", "cwd": `C:\work\shop`, "message": map[string]any{"role": "assistant", "content": blocks}}
}

func write(t *testing.T, path, data string, mod time.Time) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(data), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chtimes(path, mod, mod); err != nil {
		t.Fatal(err)
	}
}

type fixture struct {
	claudeDir, codexDir string
	claudeMain          string
	codexMain           string
	roots               []Root
	base                time.Time
}

func newFixture(t *testing.T) fixture {
	t.Helper()
	dir := t.TempDir()
	f := fixture{claudeDir: filepath.Join(dir, "claude"), codexDir: filepath.Join(dir, "codex"), base: time.Now().Add(-time.Hour).Truncate(time.Second)}
	f.roots = []Root{
		{Agent: "claude", AccountID: "default", AccountLabel: "основной", Dir: f.claudeDir},
		{Agent: "codex", AccountID: "work", AccountLabel: "Рабочий", Dir: f.codexDir},
	}

	// Claude: служебные вставки до настоящего сообщения, ответы, инструменты.
	var b strings.Builder
	b.WriteString(line(t, map[string]any{"type": "permission-mode", "permissionMode": "default", "sessionId": claudeSID}))
	b.WriteString(line(t, claudeUser("Caveat: The messages below were generated by the user while running local commands.", map[string]any{"isMeta": true})))
	b.WriteString(line(t, claudeUser("<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>", nil)))
	b.WriteString(line(t, claudeUser([]map[string]any{
		{"type": "text", "text": "<system-reminder>\nслужебное\n</system-reminder>"},
		{"type": "text", "text": "  Почини   кнопку\nвхода на телефоне"},
	}, nil)))
	b.WriteString(line(t, claudeAssistant(map[string]any{"type": "text", "text": "Готово, кнопка чинится."})))
	b.WriteString(line(t, claudeAssistant(map[string]any{"type": "tool_use", "id": "t1", "name": "Bash", "input": map[string]any{"command": "ls"}})))
	b.WriteString(line(t, claudeUser([]map[string]any{{"type": "tool_result", "tool_use_id": "t1", "content": "ok"}}, nil)))
	b.WriteString(line(t, claudeUser("ветка субагента", map[string]any{"isSidechain": true})))
	b.WriteString(line(t, map[string]any{"type": "ai-title", "aiTitle": "Кнопка входа", "sessionId": claudeSID}))
	f.claudeMain = filepath.Join(f.claudeDir, "projects", "C--work-shop", claudeSID+".jsonl")
	write(t, f.claudeMain, b.String(), f.base.Add(30*time.Minute))

	// Claude: только слеш-команда — заголовок из неё.
	write(t, filepath.Join(f.claudeDir, "projects", "C--work-other", claudeSID2+".jsonl"),
		line(t, claudeUser("<command-name>/model</command-name><command-args></command-args>", nil)),
		f.base.Add(10*time.Minute))

	// Claude: человеческого сообщения нет вовсе — заголовок из ai-title хвоста.
	write(t, filepath.Join(f.claudeDir, "projects", "C--work-other", claudeSID3+".jsonl"),
		line(t, claudeUser("<local-command-stdout>вывод</local-command-stdout>", nil))+
			line(t, map[string]any{"type": "ai-title", "aiTitle": "Старое название"})+
			line(t, map[string]any{"type": "ai-title", "aiTitle": "Разбор логов релея"}),
		f.base.Add(5*time.Minute))

	// Файл субагента старого Claude и мусор — не беседы.
	write(t, filepath.Join(f.claudeDir, "projects", "C--work-shop", "agent-abc12345.jsonl"), line(t, claudeUser("x", nil)), f.base)
	write(t, filepath.Join(f.claudeDir, "projects", "C--work-shop", "notes.txt"), "x", f.base)

	// Codex: инструкции и окружение до сообщения человека.
	var c strings.Builder
	c.WriteString(line(t, map[string]any{"type": "session_meta", "payload": map[string]any{
		"id": codexSID, "cwd": "/home/me/remotai", "source": "cli", "originator": "codex-tui",
		"base_instructions": map[string]any{"text": strings.Repeat("инструкция ", 500)}}}))
	msg := func(role, kind, text string) map[string]any {
		return map[string]any{"type": "response_item", "payload": map[string]any{"type": "message", "role": role,
			"content": []map[string]any{{"type": kind, "text": text}}}}
	}
	c.WriteString(line(t, msg("developer", "input_text", "<permissions instructions>...</permissions instructions>")))
	c.WriteString(line(t, msg("user", "input_text", "# AGENTS.md instructions for /home/me/remotai\n\n<INSTRUCTIONS>\nправила\n</INSTRUCTIONS>")))
	c.WriteString(line(t, msg("user", "input_text", "<environment_context>\n  <cwd>/home/me</cwd>\n</environment_context>")))
	c.WriteString(line(t, msg("user", "input_text", "Сделай экран всех бесед")))
	c.WriteString(line(t, map[string]any{"type": "response_item", "payload": map[string]any{"type": "function_call", "name": "shell"}}))
	c.WriteString(line(t, msg("assistant", "output_text", "Сделал.")))
	f.codexMain = filepath.Join(f.codexDir, "sessions", "2026", "09", "29", "rollout-2026-09-29T10-00-00-"+codexSID+".jsonl")
	write(t, f.codexMain, c.String(), f.base.Add(20*time.Minute))

	// Codex: субагент — скрыт.
	write(t, filepath.Join(f.codexDir, "sessions", "2026", "09", "29", "rollout-2026-09-29T11-00-00-"+codexSub+".jsonl"),
		line(t, map[string]any{"type": "session_meta", "payload": map[string]any{"id": codexSub, "cwd": "/x",
			"source": map[string]any{"subagent": map[string]any{"thread_spawn": map[string]any{}}}, "parent_thread_id": codexSID}})+
			line(t, msg("user", "input_text", "задача субагенту")),
		f.base.Add(40*time.Minute))
	return f
}

func newTestIndex(t *testing.T, state string) *Index {
	ix := NewIndex(state)
	ix.NoBackground = true
	ix.CountPause = 0
	return ix
}

func byID(p Page) map[string]Item {
	out := map[string]Item{}
	for _, it := range p.Sessions {
		out[it.SessionID] = it
	}
	return out
}

func TestListFormatsTitlesAndOrder(t *testing.T) {
	f := newFixture(t)
	ix := newTestIndex(t, "")
	page, err := ix.List(context.Background(), f.roots, nil, Query{})
	if err != nil {
		t.Fatal(err)
	}
	if page.Total != 4 || len(page.Sessions) != 4 {
		t.Fatalf("ждали 4 беседы (субагент и agent-*.jsonl скрыты), получили %d: %+v", page.Total, page.Sessions)
	}
	order := []string{page.Sessions[0].SessionID, page.Sessions[1].SessionID, page.Sessions[2].SessionID, page.Sessions[3].SessionID}
	if strings.Join(order, ",") != strings.Join([]string{claudeSID, codexSID, claudeSID2, claudeSID3}, ",") {
		t.Fatalf("свежие должны быть сверху: %v", order)
	}
	items := byID(page)
	main := items[claudeSID]
	if main.Title != "Почини кнопку входа на телефоне" || main.CWD != `C:\work\shop` || main.AccountID != "default" || main.AccountLabel != "основной" {
		t.Fatalf("беседа Claude: %+v", main)
	}
	if main.UpdatedAt != f.base.Add(30*time.Minute).UnixMilli() {
		t.Fatalf("updated_at = время файла: %d", main.UpdatedAt)
	}
	if got := items[claudeSID2].Title; got != "/model" {
		t.Fatalf("слеш-команда без текста — запасной заголовок: %q", got)
	}
	if got := items[claudeSID3].Title; got != "Разбор логов релея" {
		t.Fatalf("без сообщения человека — последний ai-title: %q", got)
	}
	cx := items[codexSID]
	if cx.Title != "Сделай экран всех бесед" || cx.CWD != "/home/me/remotai" || cx.Agent != "codex" || cx.AccountID != "work" {
		t.Fatalf("беседа Codex: %+v", cx)
	}
	if page.Agents["claude"] != 3 || page.Agents["codex"] != 1 {
		t.Fatalf("счётчики по агентам: %v", page.Agents)
	}
	if main.Messages != nil {
		t.Fatalf("до подсчёта сообщений поля быть не должно: %v", *main.Messages)
	}
}

func TestMessagesCountedIncrementally(t *testing.T) {
	f := newFixture(t)
	ix := newTestIndex(t, "")
	if _, err := ix.List(context.Background(), f.roots, nil, Query{}); err != nil {
		t.Fatal(err)
	}
	if err := ix.CountPass(context.Background()); err != nil {
		t.Fatal(err)
	}
	items := byID(mustList(t, ix, f.roots, nil, Query{}))
	// Claude: /clear, настоящее сообщение, текстовый ответ. Не считаются:
	// isMeta, вызов инструмента, его результат, ветка субагента.
	if n := items[claudeSID].Messages; n == nil || *n != 3 {
		t.Fatalf("Claude: ждали 3 сообщения, получили %v", deref(n))
	}
	// Codex: сообщение человека и ответ; инструкции и окружение — нет.
	if n := items[codexSID].Messages; n == nil || *n != 2 {
		t.Fatalf("Codex: ждали 2 сообщения, получили %v", deref(n))
	}
	// Дописали — досчитывается только новое.
	fh, err := os.OpenFile(f.claudeMain, os.O_APPEND|os.O_WRONLY, 0)
	if err != nil {
		t.Fatal(err)
	}
	_, _ = fh.WriteString(line(t, claudeUser("И ещё поправь цвет", nil)))
	// Недописанная строка: её не считаем, пока нет перевода строки.
	_, _ = fh.WriteString(`{"type":"user","message":{"role":"user","content":"полстро`)
	fh.Close()
	later := f.base.Add(50 * time.Minute)
	_ = os.Chtimes(f.claudeMain, later, later)
	mustList(t, ix, f.roots, nil, Query{})
	if err := ix.CountPass(context.Background()); err != nil {
		t.Fatal(err)
	}
	items = byID(mustList(t, ix, f.roots, nil, Query{}))
	if n := items[claudeSID].Messages; n == nil || *n != 4 {
		t.Fatalf("после дописывания ждали 4, получили %v", deref(n))
	}
	if items[claudeSID].Title != "Почини кнопку входа на телефоне" {
		t.Fatalf("голова дописыванием не меняется: %q", items[claudeSID].Title)
	}
	fh, _ = os.OpenFile(f.claudeMain, os.O_APPEND|os.O_WRONLY, 0)
	_, _ = fh.WriteString("ка\"}}\n")
	fh.Close()
	_ = os.Chtimes(f.claudeMain, later.Add(time.Minute), later.Add(time.Minute))
	mustList(t, ix, f.roots, nil, Query{})
	_ = ix.CountPass(context.Background())
	items = byID(mustList(t, ix, f.roots, nil, Query{}))
	if n := items[claudeSID].Messages; n == nil || *n != 5 {
		t.Fatalf("дописанная строка должна посчитаться один раз: %v", deref(n))
	}
}

func deref(n *int) any {
	if n == nil {
		return nil
	}
	return *n
}

func mustList(t *testing.T, ix *Index, roots []Root, open map[string]Open, q Query) Page {
	t.Helper()
	p, err := ix.List(context.Background(), roots, open, q)
	if err != nil {
		t.Fatal(err)
	}
	return p
}

func TestCacheByPathSizeMtime(t *testing.T) {
	f := newFixture(t)
	state := filepath.Join(t.TempDir(), "agent-sessions.json")
	ix := newTestIndex(t, state)
	mustList(t, ix, f.roots, nil, Query{})
	_ = ix.CountPass(context.Background())

	// Подменили содержимое, сохранив размер и время: читается кэш, а не файл.
	data, _ := os.ReadFile(f.codexMain)
	swapped := strings.Replace(string(data), "Сделай экран всех бесед", "Сделай экран ВСЕХ бесед", 1)
	if len(swapped) != len(data) {
		t.Fatal("подмена должна сохранить размер")
	}
	mod := f.base.Add(20 * time.Minute)
	write(t, f.codexMain, swapped, mod)
	if got := byID(mustList(t, ix, f.roots, nil, Query{}))[codexSID].Title; got != "Сделай экран всех бесед" {
		t.Fatalf("при тех же (размер, время) файл перечитываться не должен: %q", got)
	}

	// Кэш на диске: новый процесс не читает файлы заново, счётчики на месте.
	reopened := newTestIndex(t, state)
	items := byID(mustList(t, reopened, f.roots, nil, Query{}))
	if items[codexSID].Title != "Сделай экран всех бесед" || items[claudeSID].Messages == nil {
		t.Fatalf("кэш с диска не подхватился: %+v", items[codexSID])
	}

	// Файл переписан короче — разбираем с нуля.
	write(t, f.codexMain, line(t, map[string]any{"type": "session_meta", "payload": map[string]any{"id": codexSID, "cwd": "/new"}})+
		line(t, map[string]any{"type": "response_item", "payload": map[string]any{"type": "message", "role": "user",
			"content": []map[string]any{{"type": "input_text", "text": "Новая беседа"}}}}), mod.Add(time.Minute))
	items = byID(mustList(t, reopened, f.roots, nil, Query{}))
	if items[codexSID].Title != "Новая беседа" || items[codexSID].CWD != "/new" || items[codexSID].Messages != nil {
		t.Fatalf("переписанный файл: %+v", items[codexSID])
	}

	// Удалённый файл пропадает из списка и из кэша.
	_ = os.Remove(f.codexMain)
	if _, ok := byID(mustList(t, reopened, f.roots, nil, Query{}))[codexSID]; ok {
		t.Fatal("удалённая беседа осталась в списке")
	}
}

func TestSearchFilterAndPaging(t *testing.T) {
	f := newFixture(t)
	ix := newTestIndex(t, "")
	page := mustList(t, ix, f.roots, nil, Query{Q: "КНОПКУ телефоне"})
	if page.Total != 1 || page.Sessions[0].SessionID != claudeSID {
		t.Fatalf("поиск по заголовку без учёта регистра: %+v", page.Sessions)
	}
	page = mustList(t, ix, f.roots, nil, Query{Q: "remotai"})
	if page.Total != 1 || page.Sessions[0].SessionID != codexSID {
		t.Fatalf("поиск по папке: %+v", page.Sessions)
	}
	page = mustList(t, ix, f.roots, nil, Query{Agent: "codex"})
	if page.Total != 1 || page.Agents["claude"] != 3 {
		t.Fatalf("фильтр по агенту не должен менять счётчики чипов: %+v %v", page.Sessions, page.Agents)
	}
	page = mustList(t, ix, f.roots, nil, Query{Q: "такого нет"})
	if page.Total != 0 || page.Sessions == nil {
		t.Fatalf("пустой результат — пустой массив, не null: %+v", page)
	}

	var seen []string
	cursor := ""
	for i := 0; i < 5; i++ {
		p := mustList(t, ix, f.roots, nil, Query{Limit: 3, Cursor: cursor})
		for _, it := range p.Sessions {
			seen = append(seen, it.SessionID)
		}
		if p.Next == "" {
			break
		}
		cursor = p.Next
	}
	if len(seen) != 4 || seen[3] != claudeSID3 {
		t.Fatalf("страницы должны пройти список ровно один раз: %v", seen)
	}
}

func TestOpenAndRunningMarks(t *testing.T) {
	f := newFixture(t)
	ix := newTestIndex(t, "")
	// Живой Claude вне Remotai держит вторую беседу. Рядом ключ — его не
	// открываем (проверяем, что мусорное имя не ломает разбор).
	write(t, filepath.Join(f.claudeDir, "sessions", "4242.json"), `{"pid":4242,"sessionId":"`+claudeSID2+`"}`, f.base)
	write(t, filepath.Join(f.claudeDir, "sessions", "4243.json"), `{"pid":4243,"sessionId":"`+claudeSID3+`"}`, f.base)
	write(t, filepath.Join(f.claudeDir, "sessions", "4242.abc.key"), `secret`, f.base)
	ix.PIDAlive = func(pid int) bool { return pid == 4242 }
	open := map[string]Open{
		Key("claude", claudeSID): {PtyID: "pty-1"},
		Key("codex", codexSID):   {PtyID: "pty-2", Sleeping: true},
	}
	items := byID(mustList(t, ix, f.roots, open, Query{}))
	if items[claudeSID].OpenPtyID != "pty-1" || items[claudeSID].Sleeping {
		t.Fatalf("идущая беседа: %+v", items[claudeSID])
	}
	if items[codexSID].OpenPtyID != "pty-2" || !items[codexSID].Sleeping {
		t.Fatalf("спящая беседа: %+v", items[codexSID])
	}
	if !items[claudeSID2].Running || items[claudeSID2].OpenPtyID != "" {
		t.Fatalf("беседа живого Claude вне Remotai: %+v", items[claudeSID2])
	}
	if items[claudeSID3].Running {
		t.Fatal("мёртвый PID не делает беседу открытой")
	}
}

func TestSameDirUnderTwoAccountsListedOnce(t *testing.T) {
	f := newFixture(t)
	ix := newTestIndex(t, "")
	roots := append([]Root{}, f.roots...)
	roots = append(roots, Root{Agent: "claude", AccountID: "dup", Dir: f.claudeDir})
	if page := mustList(t, ix, roots, nil, Query{}); page.Total != 4 {
		t.Fatalf("один каталог у двух записей — беседы один раз: %d", page.Total)
	}
}

func TestHumanText(t *testing.T) {
	cases := []struct{ in, title, cmd string }{
		{"Просто текст", "Просто текст", ""},
		{"<system-reminder>x</system-reminder>\n\nНастоящее", "Настоящее", ""},
		{"<local-command-stdout>вывод</local-command-stdout>", "", ""},
		{"<command-name>/review</command-name><command-args>PR 12</command-args>", "/review PR 12", ""},
		{"<command-name>/clear</command-name><command-args></command-args>", "", "/clear"},
		{"<pasted_content>длинная вставка", "", ""},
		{"# AGENTS.md instructions for /x", "", ""},
		{"[Request interrupted by user]", "", ""},
		{"   ", "", ""},
		{"Глянь скрин <image name=[Image #1]></image> и поправь", "Глянь скрин и поправь", ""},
	}
	for _, c := range cases {
		title, cmd := humanText(c.in)
		if title != c.title || cmd != c.cmd {
			t.Errorf("humanText(%q) = %q,%q; ждали %q,%q", c.in, title, cmd, c.title, c.cmd)
		}
	}
	long := strings.Repeat("я", 300)
	got, _ := humanText(long)
	if n := len([]rune(got)); n != titleRunes || !strings.HasSuffix(got, "…") {
		t.Fatalf("заголовок режется до %d символов с многоточием: %d", titleRunes, n)
	}
}

func TestHugeLinesAndHeadCapBounded(t *testing.T) {
	dir := t.TempDir()
	root := Root{Agent: "claude", AccountID: "default", Dir: dir}
	// Первая строка — огромная вставка (больше maxLine), дальше настоящее
	// сообщение. Огромную пропускаем, а не падаем и не держим в памяти.
	big := line(t, claudeUser(strings.Repeat("b", maxLine), nil))
	write(t, filepath.Join(dir, "projects", "p", claudeSID+".jsonl"), big+line(t, claudeUser("После вставки", nil)), time.Now())
	ix := newTestIndex(t, "")
	items := byID(mustList(t, ix, []Root{root}, nil, Query{}))
	if items[claudeSID].Title != "После вставки" {
		t.Fatalf("строку длиннее maxLine надо пропустить: %+v", items[claudeSID])
	}
	_ = ix.CountPass(context.Background())
	items = byID(mustList(t, ix, []Root{root}, nil, Query{}))
	if n := items[claudeSID].Messages; n == nil || *n != 1 {
		t.Fatalf("огромная строка в счёт не идёт: %v", deref(n))
	}
}

func TestListBudgetGivesPartial(t *testing.T) {
	f := newFixture(t)
	ix := newTestIndex(t, "")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	page, err := ix.List(ctx, f.roots, nil, Query{})
	if err != nil {
		t.Fatal(err)
	}
	if !page.Partial || page.Total != 0 {
		t.Fatalf("без времени на разбор — partial и пустой список: %+v", page)
	}
}

// Сообщения считаются только у бесед отданной страницы: полный проход по всем
// файлам на ПК владельца — это ~13 ГБ чтения после каждого запуска Remotai.
func TestCountPassOnlyVisiblePage(t *testing.T) {
	f := newFixture(t)
	ix := newTestIndex(t, "")
	page := mustList(t, ix, f.roots, nil, Query{Limit: 1})
	if len(page.Sessions) != 1 || page.Total < 2 {
		t.Fatalf("нужна страница из одной беседы при нескольких: %+v", page)
	}
	if err := ix.CountPass(context.Background()); err != nil {
		t.Fatal(err)
	}
	counted := 0
	for _, it := range mustList(t, ix, f.roots, nil, Query{}).Sessions {
		if it.Messages != nil {
			counted++
			if it.SessionID != page.Sessions[0].SessionID {
				t.Fatalf("посчитана беседа вне страницы: %s", it.SessionID)
			}
		}
	}
	if counted != 1 {
		t.Fatalf("посчитано %d бесед, ждали одну видимую", counted)
	}
}
