package agenthistory

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
	"unicode/utf8"

	"tgcontrol/internal/procutil"
)

type codexCursor struct {
	Source, Cursor string
	// Before is an exclusive UTF-8 byte boundary within the same upstream
	// batch. Fingerprint rejects changes while walking its older chunks.
	Before      int    `json:",omitempty"`
	Fingerprint string `json:",omitempty"`
}

func codexCommand(ctx context.Context, binary string, args ...string) *exec.Cmd {
	var cmd *exec.Cmd
	if runtime.GOOS == "windows" && (strings.HasSuffix(strings.ToLower(binary), ".cmd") || strings.HasSuffix(strings.ToLower(binary), ".bat")) {
		cmd = exec.CommandContext(ctx, "cmd.exe", append([]string{"/d", "/s", "/c", binary}, args...)...)
	} else {
		cmd = exec.CommandContext(ctx, binary, args...)
	}
	procutil.Hidden(cmd)
	procutil.Prepare(cmd)
	return cmd
}

// Versioned read-only app-server API, verified against the schema generated by
// codex-cli 0.154.0. No thread/start, thread/resume or turn/start is sent.
func readCodex(ctx context.Context, source Source, cursor, binary string) (Page, error) {
	page := Page{Source: source.Key(), Agent: "codex", Version: "0.154.0", Schema: "codex-app-server-turns-v2"}
	if binary == "" || !filepath.IsAbs(source.ConfigHome) {
		return page, ErrUnavailable
	}
	c := codexCursor{Source: page.Source}
	if cursor != "" && (decodeCursor(cursor, &c) != nil || c.Source != page.Source) {
		return page, ErrChanged
	}
	ctx, cancel := context.WithTimeout(ctx, 12*time.Second)
	defer cancel()
	version := codexCommand(ctx, binary, "--version")
	var versionOut cappedOutput
	versionOut.limit = 1024
	version.Stdout = &versionOut
	version.Stderr = io.Discard
	if version.Run() != nil {
		return page, ErrUnavailable
	}
	if reported := strings.TrimSpace(versionOut.String()); reported != "codex-cli 0.154.0" {
		// Узнаваемый ответ другой версии — отдельный код с версией (ST-10 B);
		// незнакомый вывод вообще — прежний «формат не поддержан».
		if other, ok := strings.CutPrefix(reported, "codex-cli "); ok && other != "" && !strings.ContainsAny(other, " \r\n") {
			return page, versionError("codex", other)
		}
		return page, ErrFormat
	}
	cmd := codexCommand(ctx, binary, "app-server", "--listen", "stdio://")
	if source.ConfigHome != "" {
		cmd.Env = []string{}
		for _, value := range os.Environ() {
			if !strings.HasPrefix(strings.ToUpper(value), "CODEX_HOME=") {
				cmd.Env = append(cmd.Env, value)
			}
		}
		cmd.Env = append(cmd.Env, "CODEX_HOME="+source.ConfigHome)
	}
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return page, ErrUnavailable
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		stdin.Close()
		return page, ErrUnavailable
	}
	cmd.Stderr = io.Discard
	if err := cmd.Start(); err != nil {
		stdin.Close()
		return page, ErrUnavailable
	}
	defer func() { stdin.Close(); _ = procutil.KillTree(cmd); _ = cmd.Wait() }()
	rpc := json.NewEncoder(stdin)
	scanner := bufio.NewScanner(io.LimitReader(stdout, 16<<20))
	scanner.Buffer(make([]byte, 4096), 8<<20)
	if rpc.Encode(map[string]any{"id": 1, "method": "initialize", "params": map[string]any{
		"clientInfo": map[string]string{"name": "remotai_history", "version": "1"}, "capabilities": map[string]bool{"experimentalApi": true},
	}}) != nil {
		return page, ErrUnavailable
	}
	if _, err := readRPC(scanner, 1); err != nil {
		return page, err
	}
	if rpc.Encode(map[string]any{"method": "initialized", "params": map[string]any{}}) != nil {
		return page, ErrUnavailable
	}
	params := map[string]any{"threadId": source.SessionID, "limit": 20, "sortDirection": "desc", "itemsView": "full"}
	if c.Cursor != "" {
		params["cursor"] = c.Cursor
	}
	if rpc.Encode(map[string]any{"id": 2, "method": "thread/turns/list", "params": params}) != nil {
		return page, ErrUnavailable
	}
	result, err := readRPC(scanner, 2)
	if err != nil {
		return page, err
	}
	return codexPage(page, result, c)
}

type cappedOutput struct {
	bytes.Buffer
	limit int
}

func (b *cappedOutput) Write(p []byte) (int, error) {
	n := len(p)
	_, _ = b.Buffer.Write(p[:min(n, max(0, b.limit-b.Len()))])
	return n, nil
}

func readRPC(scanner *bufio.Scanner, id int) (json.RawMessage, error) {
	for count := 0; count < 64 && scanner.Scan(); count++ {
		var reply struct {
			ID            *int
			Result, Error json.RawMessage
		}
		if json.Unmarshal(scanner.Bytes(), &reply) != nil {
			return nil, ErrFormat
		}
		if reply.ID == nil || *reply.ID != id {
			continue
		}
		if len(reply.Error) > 0 && string(reply.Error) != "null" {
			return nil, ErrUnavailable
		}
		if len(reply.Result) == 0 {
			return nil, ErrFormat
		}
		return reply.Result, nil
	}
	return nil, ErrUnavailable
}

func codexPage(page Page, raw json.RawMessage, cursors ...codexCursor) (Page, error) {
	cursor := codexCursor{Source: page.Source}
	if len(cursors) > 0 {
		cursor = cursors[0]
	}
	if cursor.Source != page.Source || cursor.Before < 0 || (cursor.Before == 0) != (cursor.Fingerprint == "") {
		return page, ErrChanged
	}
	var response struct {
		Data []struct {
			Items []struct {
				Type, Text, Command string
				Server, Tool        string
				Arguments           json.RawMessage
				Changes             []struct{ Path, Diff string }
				Result              *struct{ Content, StructuredContent json.RawMessage }
				Error               *struct{ Message string }
				Content             json.RawMessage
				AggregatedOutput    *string
			}
		}
		NextCursor *string
	}
	if json.Unmarshal(raw, &response) != nil || response.Data == nil || len(response.Data) > 20 {
		return page, ErrFormat
	}
	parts := []string{}
	// Turns arrive newest-first; items within a turn retain their recorded order.
	for turn := len(response.Data) - 1; turn >= 0; turn-- {
		if response.Data[turn].Items == nil {
			page.Partial = true
		}
		for _, item := range response.Data[turn].Items {
			text := ""
			switch item.Type {
			case "userMessage":
				value, omitted := visibleContent(item.Content)
				page.Partial = page.Partial || omitted
				text = "[user]\n" + value
			case "agentMessage":
				text = "[assistant]\n" + item.Text
			case "commandExecution":
				text = "[command]\n" + item.Command
				if item.AggregatedOutput != nil {
					text += "\n" + *item.AggregatedOutput
				}
			case "fileChange":
				for _, change := range item.Changes {
					text += "[file: " + change.Path + "]\n" + change.Diff + "\n"
				}
			case "mcpToolCall":
				text = "[tool: " + item.Server + "/" + item.Tool + "]\n" + string(item.Arguments)
				if item.Result != nil {
					value, omitted := visibleContent(item.Result.Content)
					page.Partial = page.Partial || omitted
					text += "\n" + value
					if len(item.Result.StructuredContent) > 0 && string(item.Result.StructuredContent) != "null" {
						text += "\n" + string(item.Result.StructuredContent)
					}
				}
				if item.Error != nil {
					text += "\n[error]\n" + item.Error.Message
				}
			default:
				page.Partial = true
			}
			if text != "" {
				parts = append(parts, text)
			}
		}
	}
	text := strings.Join(parts, "\n\n")
	// Begin at the newest end. A large older tool item must never displace the
	// last answer. Local cursors revisit this upstream batch until all of its
	// text has been read, before advancing to the upstream older-turn cursor.
	digest := sha256.Sum256(raw)
	fingerprint := hex.EncodeToString(digest[:])
	end := len(text)
	if cursor.Before > 0 {
		if cursor.Fingerprint != fingerprint || cursor.Before > end ||
			(cursor.Before < end && !utf8.RuneStart(text[cursor.Before])) {
			return page, ErrChanged
		}
		end = cursor.Before
	}
	start := max(0, end-MaxText)
	for start < end && !utf8.RuneStart(text[start]) {
		start++
	}
	page.Text = text[start:end]
	page.Partial = page.Partial || start > 0 || end < len(text)
	page.Next = ""
	if start > 0 {
		page.Next = encodeCursor(codexCursor{Source: page.Source, Cursor: cursor.Cursor, Before: start, Fingerprint: fingerprint})
	} else if response.NextCursor != nil && *response.NextCursor != "" {
		page.Next = encodeCursor(codexCursor{Source: page.Source, Cursor: *response.NextCursor})
	}
	return page, nil
}
