package bot

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"

	"github.com/go-telegram/bot"
	"github.com/go-telegram/bot/models"

	"tgcontrol/internal/sessions"
)

// shareActionsKB builds the inline keyboard shown after a file is saved via the
// bot's "share to TGControl" flow. The file path is registered into the bot's
// per-user path registry and referenced by index to keep callback_data short
// (Telegram limits it to 64 bytes).
func (tb *Bot) shareActionsKB(uid int64, savedPath string) *models.InlineKeyboardMarkup {
	idx := tb.pid(uid, savedPath)
	return &models.InlineKeyboardMarkup{
		InlineKeyboard: [][]models.InlineKeyboardButton{
			{
				{Text: "📂 Открыть папку", CallbackData: fmt.Sprintf("sh:of:%d", idx)},
				{Text: "🗑 Удалить", CallbackData: fmt.Sprintf("sh:rm:%d", idx)},
			},
			{
				{Text: "🖥 В терминал", CallbackData: fmt.Sprintf("sh:tt:%d", idx)},
				{Text: "🤖 В сессию", CallbackData: fmt.Sprintf("sh:ts:%d", idx)},
			},
		},
	}
}

// onShareCB handles all sh: callbacks generated by the share flow.
func (tb *Bot) onShareCB(ctx context.Context, b *bot.Bot, update *models.Update) {
	query := update.CallbackQuery
	b.AnswerCallbackQuery(ctx, &bot.AnswerCallbackQueryParams{CallbackQueryID: query.ID})
	uid := query.From.ID
	if !tb.authorized(uid) {
		return
	}

	data := query.Data
	parts := strings.SplitN(data, ":", 4)
	if len(parts) < 3 {
		tb.answerCB(ctx, update, "❓ Неверный формат callback.")
		return
	}
	action := parts[1]

	// All actions need the saved file path.
	idx, err := strconv.Atoi(parts[2])
	if err != nil {
		tb.answerCB(ctx, update, "❓ Неверный индекс файла.")
		return
	}
	savedPath := tb.pget(uid, idx)
	if savedPath == "" {
		tb.answerCB(ctx, update, "⚠️ Файл больше недоступен (бот перезапущен).")
		return
	}

	switch action {
	case "of": // open folder on PC
		dir := filepath.Dir(savedPath)
		if err := openFolder(dir); err != nil {
			tb.answerCB(ctx, update, "❌ Не удалось открыть папку: "+esc(err.Error()))
			return
		}
		tb.answerCB(ctx, update, fmt.Sprintf("📂 Открыто: <code>%s</code>", esc(dir)))

	case "rm": // delete file
		if err := os.Remove(savedPath); err != nil {
			tb.answerCB(ctx, update, "❌ Не удалось удалить: "+esc(err.Error()))
			return
		}
		tb.answerCB(ctx, update, fmt.Sprintf("🗑 Удалено: <code>%s</code>", esc(filepath.Base(savedPath))))

	case "tt": // pick a terminal (PTY) — show selector
		tb.showShareTerminalPicker(ctx, update, uid, idx)

	case "ts": // pick an AI session — show selector
		tb.showShareSessionPicker(ctx, update, uid, idx)

	case "ttp": // terminal picked: parts[3] = pty id
		if len(parts) < 4 {
			tb.answerCB(ctx, update, "❓ Не указан терминал.")
			return
		}
		tb.attachToPty(ctx, update, uid, savedPath, parts[3])

	case "tsp": // session picked: parts[3] = session name
		if len(parts) < 4 {
			tb.answerCB(ctx, update, "❓ Не указана сессия.")
			return
		}
		tb.attachToSession(ctx, update, uid, savedPath, parts[3])

	default:
		tb.answerCB(ctx, update, "❓ Неизвестное действие: "+esc(action))
	}
}

// showShareTerminalPicker lists active PTY terminals to attach the file to.
func (tb *Bot) showShareTerminalPicker(ctx context.Context, update *models.Update, uid int64, fileIdx int) {
	if tb.webServer == nil {
		tb.answerCB(ctx, update, "⚠️ Терминалы недоступны.")
		return
	}
	manager := tb.webServer.PtyManager()
	if manager == nil {
		tb.answerCB(ctx, update, "⚠️ Менеджер PTY не инициализирован.")
		return
	}
	ptys := manager.List()
	if len(ptys) == 0 {
		tb.answerCB(ctx, update, "📭 Нет открытых терминалов.\nОткройте PTY на устройстве и попробуйте снова.")
		return
	}

	rows := make([][]models.InlineKeyboardButton, 0, len(ptys)+1)
	for _, p := range ptys {
		label := fmt.Sprintf("🖥 %s — %s", shortPath(p.CWD), shortShellName(p.Shell))
		rows = append(rows, []models.InlineKeyboardButton{{
			Text:         label,
			CallbackData: fmt.Sprintf("sh:ttp:%d:%s", fileIdx, p.ID),
		}})
	}
	rows = append(rows, []models.InlineKeyboardButton{{
		Text: "« Назад", CallbackData: fmt.Sprintf("sh:back:%d", fileIdx),
	}})
	tb.answerCB(ctx, update, "🖥 <b>В какой терминал?</b>", &models.InlineKeyboardMarkup{InlineKeyboard: rows})
}

// showShareSessionPicker lists existing AI sessions to attach the file to.
func (tb *Bot) showShareSessionPicker(ctx context.Context, update *models.Update, uid int64, fileIdx int) {
	list := tb.store.List(int(uid))
	if len(list) == 0 {
		tb.answerCB(ctx, update, "📭 Нет сессий. Создайте: /new")
		return
	}

	rows := make([][]models.InlineKeyboardButton, 0, len(list)+1)
	for _, s := range list {
		label := fmt.Sprintf("🤖 %s (%s)", s.Name, s.AgentType)
		rows = append(rows, []models.InlineKeyboardButton{{
			Text:         label,
			CallbackData: fmt.Sprintf("sh:tsp:%d:%s", fileIdx, s.Name),
		}})
	}
	rows = append(rows, []models.InlineKeyboardButton{{
		Text: "« Назад", CallbackData: fmt.Sprintf("sh:back:%d", fileIdx),
	}})
	tb.answerCB(ctx, update, "🤖 <b>В какую сессию?</b>", &models.InlineKeyboardMarkup{InlineKeyboard: rows})
}

// attachToPty copies the file into the PTY's cwd (if different from the saved
// location) and pastes a "view file" command into the shell.
func (tb *Bot) attachToPty(ctx context.Context, update *models.Update, uid int64, savedPath, ptyID string) {
	manager := tb.webServer.PtyManager()
	if manager == nil {
		tb.answerCB(ctx, update, "⚠️ PTY-менеджер недоступен.")
		return
	}
	sess := manager.Get(ptyID)
	if sess == nil {
		tb.answerCB(ctx, update, "⚠️ Терминал не найден (закрыт?).")
		return
	}

	// If the file is already inside the PTY's cwd, no need to copy.
	finalPath := savedPath
	if !strings.HasPrefix(strings.ToLower(savedPath), strings.ToLower(sess.CWD)+string(filepath.Separator)) {
		dst := uniqueFilename(sess.CWD, filepath.Base(savedPath))
		if err := copyFile(savedPath, dst); err != nil {
			tb.answerCB(ctx, update, "❌ Не удалось скопировать файл: "+esc(err.Error()))
			return
		}
		finalPath = dst
	}

	// Paste a "view" command appropriate for the shell. We send raw bytes; the
	// user can run/edit it manually before pressing Enter.
	rel, err := filepath.Rel(sess.CWD, finalPath)
	if err != nil || strings.HasPrefix(rel, "..") {
		rel = finalPath
	}
	cmd := buildViewCommand(sess.Shell, rel)
	if _, err := sess.Write([]byte(cmd)); err != nil {
		tb.answerCB(ctx, update, "❌ Не удалось вставить команду: "+esc(err.Error()))
		return
	}

	tb.answerCB(ctx, update, fmt.Sprintf(
		"✅ Файл вставлен в терминал.\n📂 <code>%s</code>", esc(finalPath)))
}

// attachToSession queues an "attached file" message into the AI session.
// Sends a synthetic prompt that includes the path so the agent picks it up.
func (tb *Bot) attachToSession(ctx context.Context, update *models.Update, uid int64, savedPath, sessionName string) {
	sess := tb.store.Get(int(uid), sessionName)
	if sess == nil {
		tb.answerCB(ctx, update, "❌ Сессия не найдена: "+esc(sessionName))
		return
	}

	// If saved file lives outside the session cwd, copy it in.
	finalPath := savedPath
	if sess.Cwd != "" && !strings.HasPrefix(strings.ToLower(savedPath), strings.ToLower(sess.Cwd)+string(filepath.Separator)) {
		dst := uniqueFilename(sess.Cwd, filepath.Base(savedPath))
		if err := copyFile(savedPath, dst); err == nil {
			finalPath = dst
		}
	}

	rel := finalPath
	if sess.Cwd != "" {
		if r, err := filepath.Rel(sess.Cwd, finalPath); err == nil && !strings.HasPrefix(r, "..") {
			rel = r
		}
	}

	prompt := fmt.Sprintf("Я прикрепил файл: %s — посмотри его и расскажи, что можем с ним сделать.", rel)
	chatID := getChatID(update)
	threadID := getThreadID(update)
	tb.answerCB(ctx, update, fmt.Sprintf(
		"🤖 Передаю в сессию <b>%s</b>...\n📂 <code>%s</code>", esc(sessionName), esc(finalPath)))
	go tb.sendPromptToAgent(ctx, uid, chatID, prompt, threadID, sessionName)
}

// resolveTopicCwd returns the cwd of a topic-bound session if the message came
// from a Telegram forum topic that's bound. Returns "" if no binding.
func (tb *Bot) resolveTopicCwd(uid, chatID int64, threadID int) (cwd string, sessionName string) {
	if threadID == 0 {
		return "", ""
	}
	key := sessions.TopicKey(chatID, threadID)
	binding := tb.topics.Get(key)
	if binding == nil {
		return "", ""
	}
	sess := tb.ensureTopicSession(uid, binding, threadID)
	if sess == nil {
		return binding.Cwd, ""
	}
	return sess.Cwd, sess.Name
}

// ── platform helpers ────────────────────────────────────────────────────

// openFolder opens a directory in the host file manager.
//
// Окно здесь НЕ гасим: показать папку человеку у ПК — и есть смысл действия
// (кнопка «Открыть папку» в чате бота). Консольной вспышки тут и не бывает —
// explorer/open/xdg-open оконные, своей консоли не создают.
func openFolder(dir string) error {
	switch runtime.GOOS {
	case "windows":
		return exec.Command("explorer", dir).Start()
	case "darwin":
		return exec.Command("open", dir).Start()
	default:
		return exec.Command("xdg-open", dir).Start()
	}
}

// copyFile copies src to dst with default file mode.
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	defer out.Close()

	buf := make([]byte, 64*1024)
	for {
		n, rerr := in.Read(buf)
		if n > 0 {
			if _, werr := out.Write(buf[:n]); werr != nil {
				return werr
			}
		}
		if rerr != nil {
			if rerr.Error() == "EOF" {
				return nil
			}
			break
		}
	}
	return nil
}

// buildViewCommand returns a shell-appropriate "view this file" command,
// including a trailing newline-less typing so the user reviews before pressing Enter.
func buildViewCommand(shellPath, fileRelPath string) string {
	low := strings.ToLower(filepath.Base(shellPath))
	switch {
	case strings.Contains(low, "powershell"), strings.Contains(low, "pwsh"):
		// PowerShell: Get-Content for text-like, Get-Item otherwise. Default to Get-Content.
		return fmt.Sprintf("Get-Content -Path \"%s\" | Select-Object -First 50", fileRelPath)
	case strings.Contains(low, "cmd"):
		return fmt.Sprintf("type \"%s\"", fileRelPath)
	default:
		// bash/zsh/fish — use cat with line limit.
		return fmt.Sprintf("head -n 50 \"%s\"", fileRelPath)
	}
}

// shortPath truncates very long paths for display in inline keyboard buttons.
func shortPath(p string) string {
	if len(p) <= 32 {
		return p
	}
	return "…" + p[len(p)-31:]
}

// shortShellName returns the basename of a shell path without extension.
func shortShellName(shell string) string {
	base := filepath.Base(shell)
	if ext := filepath.Ext(base); ext != "" {
		base = strings.TrimSuffix(base, ext)
	}
	return base
}
